export const enum TokenType {
  Text = 0,
  LessThan = 1,
  GreaterThan = 2,
  Slash = 3,
  Equals = 4,
  TagName = 5,
  AttributeName = 6,
  AttributeValue = 7,
  Quote = 8,
  Whitespace = 9,
  CommentStart = 10,
  CommentEnd = 11,
  BladeCommentStart = 12,
  BladeCommentEnd = 13,
  DoctypeStart = 14,
  Doctype = 15,
  DoctypeEnd = 16,
  AtSign = 17,
  EchoStart = 18,
  EchoEnd = 19,
  EchoContent = 20,
  RawEchoStart = 21,
  RawEchoEnd = 22,
  TripleEchoStart = 23,
  TripleEchoEnd = 24,
  Directive = 25,
  DirectiveArgs = 26,
  VerbatimStart = 27,
  VerbatimEnd = 28,
  PhpBlockStart = 29,
  PhpBlockEnd = 30,
  PhpBlock = 31,
  SyntheticClose = 32,
  EscapedAttribute = 33,
  BoundAttribute = 34,
  ShorthandAttribute = 35,
  BogusComment = 36,
  ConditionalCommentStart = 37,
  ConditionalCommentEnd = 38,
  PhpTagStart = 39,
  PhpTagEnd = 40,
  PhpContent = 41,
  CdataStart = 42,
  CdataEnd = 43,
  DeclStart = 44,
  DeclEnd = 45,
  PIStart = 46,
  PIEnd = 47,
  JsxAttributeValue = 48,
  JsxShorthandAttribute = 49,
  TsxGenericType = 50,
}

export const TOKEN_LABELS: Record<number, string> = {
  [0]: "Text",
  [1]: "LessThan",
  [2]: "GreaterThan",
  [3]: "Slash",
  [4]: "Equals",
  [5]: "TagName",
  [6]: "AttributeName",
  [7]: "AttributeValue",
  [8]: "Quote",
  [9]: "Whitespace",
  [10]: "CommentStart",
  [11]: "CommentEnd",
  [12]: "BladeCommentStart",
  [13]: "BladeCommentEnd",
  [14]: "DoctypeStart",
  [15]: "Doctype",
  [16]: "DoctypeEnd",
  [17]: "AtSign",
  [18]: "EchoStart",
  [19]: "EchoEnd",
  [20]: "EchoContent",
  [21]: "RawEchoStart",
  [22]: "RawEchoEnd",
  [23]: "TripleEchoStart",
  [24]: "TripleEchoEnd",
  [25]: "Directive",
  [26]: "DirectiveArgs",
  [27]: "VerbatimStart",
  [28]: "VerbatimEnd",
  [29]: "PhpBlockStart",
  [30]: "PhpBlockEnd",
  [31]: "PhpBlock",
  [32]: "SyntheticClose",
  [33]: "EscapedAttribute",
  [34]: "BoundAttribute",
  [35]: "ShorthandAttribute",
  [36]: "BogusComment",
  [37]: "ConditionalCommentStart",
  [38]: "ConditionalCommentEnd",
  [39]: "PhpTagStart",
  [40]: "PhpTagEnd",
  [41]: "PhpContent",
  [42]: "CdataStart",
  [43]: "CdataEnd",
  [44]: "DeclStart",
  [45]: "DeclEnd",
  [46]: "PIStart",
  [47]: "PIEnd",
  [48]: "JsxAttributeValue",
  [49]: "JsxShorthandAttribute",
  [50]: "TsxGenericType",
};

export function tokenLabel(type: number): string {
  return TOKEN_LABELS[type] ?? `Unknown(${type})`;
}

export interface Token {
  type: TokenType;
  start: number;
  end: number;
}

export const enum State {
  Data = 0,
  TagOpen = 1,
  TagName = 2,
  BeforeAttrName = 3,
  AttrName = 4,
  AfterAttrName = 5,
  BeforeAttrValue = 6,
  AttrValueQuoted = 7,
  AttrValueUnquoted = 8,
  RawText = 9,
  Comment = 10,
  BladeComment = 11,
}
