import { describe, it } from "vitest";
import bladePlugin from "../../src/index.js";
import * as phpPlugin from "@prettier/plugin-php";
import { formatEqual } from "../helpers.js";

const WITH_PHP = {
  plugins: [bladePlugin, phpPlugin],
  bladePhpFormatting: "safe" as const,
  singleQuote: true,
};

describe("directives/body-blank-lines", () => {
  it.each([
    {
      name: "php block then directive",
      input: [
        "@foreach ($items as $item)",
        "@php",
        "$x = 1;",
        "@endphp",
        "",
        "@livewire($x)",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  @php",
        "    $x = 1;",
        "  @endphp",
        "",
        "  @livewire ($x)",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "verbatim block then directive",
      input: [
        "@foreach ($items as $item)",
        "@verbatim",
        "{{ raw }}",
        "@endverbatim",
        "",
        "@livewire($item)",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  @verbatim",
        "{{ raw }}",
        "@endverbatim",
        "",
        "  @livewire ($item)",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "nested directive block then directive",
      input: [
        "@foreach ($items as $item)",
        "@if ($item->visible)",
        "<span>{{ $item->label }}</span>",
        "@endif",
        "",
        "@livewire($item)",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  @if ($item->visible)",
        "    <span>{{ $item->label }}</span>",
        "  @endif",
        "",
        "  @livewire ($item)",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "directive then nested directive block",
      input: [
        "@foreach ($items as $item)",
        "@livewire($item)",
        "",
        "@if ($item->visible)",
        "<span>{{ $item->label }}</span>",
        "@endif",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  @livewire ($item)",
        "",
        "  @if ($item->visible)",
        "    <span>{{ $item->label }}</span>",
        "  @endif",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "element then directive",
      input: [
        "@foreach ($items as $item)",
        "<div>{{ $item->label }}</div>",
        "",
        "@livewire($item)",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  <div>{{ $item->label }}</div>",
        "",
        "  @livewire ($item)",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "echo then directive",
      input: [
        "@foreach ($items as $item)",
        "{{ $item->label }}",
        "",
        "@livewire($item)",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  {{ $item->label }}",
        "",
        "  @livewire ($item)",
        "@endforeach",
        "",
      ].join("\n"),
    },
    {
      name: "directive then php block",
      input: [
        "@foreach ($items as $item)",
        "@livewire($item)",
        "",
        "@php",
        "$x = 1;",
        "@endphp",
        "@endforeach",
        "",
      ].join("\n"),
      expected: [
        "@foreach ($items as $item)",
        "  @livewire ($item)",
        "",
        "  @php",
        "    $x = 1;",
        "  @endphp",
        "@endforeach",
        "",
      ].join("\n"),
    },
  ])(
    "preserves authored blank lines between mixed body siblings: $name",
    async ({ input, expected }) => {
      await formatEqual(input, expected, WITH_PHP, 3);
    },
  );

  it.each([
    {
      name: "section",
      input: [
        "@section('content')",
        "<x-header />",
        "",
        "@php",
        "$title = $post->title;",
        "@endphp",
        "@endsection",
        "",
      ].join("\n"),
      expected: [
        "@section ('content')",
        "  <x-header />",
        "",
        "  @php",
        "    $title = $post->title;",
        "  @endphp",
        "@endsection",
        "",
      ].join("\n"),
    },
    {
      name: "component",
      input: [
        "@component('mail::message')",
        "@php",
        "$total = $order->total();",
        "@endphp",
        "",
        '<x-summary :total="$total" />',
        "@endcomponent",
        "",
      ].join("\n"),
      expected: [
        "@component ('mail::message')",
        "  @php",
        "    $total = $order->total();",
        "  @endphp",
        "",
        '  <x-summary :total="$total" />',
        "@endcomponent",
        "",
      ].join("\n"),
    },
    {
      name: "for",
      input: [
        "@for ($i = 0; $i < 2; $i++)",
        "@php",
        "$value = $items[$i];",
        "@endphp",
        "",
        '<x-row :value="$value" />',
        "@endfor",
        "",
      ].join("\n"),
      expected: [
        "@for ($i = 0; $i < 2; $i++)",
        "  @php",
        "    $value = $items[$i];",
        "  @endphp",
        "",
        '  <x-row :value="$value" />',
        "@endfor",
        "",
      ].join("\n"),
    },
    {
      name: "forelse primary branch",
      input: [
        "@forelse ($items as $item)",
        '<x-row :item="$item" />',
        "",
        "@include('partials.row-actions')",
        "@empty",
        "<p>No items.</p>",
        "@endforelse",
        "",
      ].join("\n"),
      expected: [
        "@forelse ($items as $item)",
        '  <x-row :item="$item" />',
        "",
        "  @include ('partials.row-actions')",
        "@empty",
        "  <p>No items.</p>",
        "@endforelse",
        "",
      ].join("\n"),
    },
    {
      name: "push",
      input: [
        "@push('scripts')",
        "@vite('resources/js/app.js')",
        "",
        "<script>",
        "window.ready = true;",
        "</script>",
        "@endpush",
        "",
      ].join("\n"),
      expected: [
        "@push ('scripts')",
        "  @vite ('resources/js/app.js')",
        "",
        "  <script>",
        "    window.ready = true;",
        "  </script>",
        "@endpush",
        "",
      ].join("\n"),
    },
    {
      name: "fragment",
      input: [
        "@fragment('modal')",
        "<x-modal />",
        "",
        "@livewire('settings.modal')",
        "@endfragment",
        "",
      ].join("\n"),
      expected: [
        "@fragment ('modal')",
        "  <x-modal />",
        "",
        "  @livewire ('settings.modal')",
        "@endfragment",
        "",
      ].join("\n"),
    },
    {
      name: "switch case",
      input: [
        "@switch($type)",
        "@case('a')",
        "@php",
        "$label = $type;",
        "@endphp",
        "",
        "<p>{{ $label }}</p>",
        "@break",
        "@default",
        "<p>Unknown</p>",
        "@endswitch",
        "",
      ].join("\n"),
      expected: [
        "@switch ($type)",
        "  @case ('a')",
        "    @php",
        "      $label = $type;",
        "    @endphp",
        "",
        "    <p>{{ $label }}</p>",
        "    @break",
        "  @default",
        "    <p>Unknown</p>",
        "@endswitch",
        "",
      ].join("\n"),
    },
  ])(
    "preserves authored blank lines inside representative block directive bodies: $name",
    async ({ input, expected }) => {
      await formatEqual(input, expected, WITH_PHP, 3);
    },
  );

  it("does not duplicate branch separator blank lines while preserving body sibling gaps", async () => {
    const input = [
      "@if($ready)",
      "@php",
      "$state = 'ready';",
      "@endphp",
      "",
      "@else",
      "<p>Waiting</p>",
      "",
      "@endif",
      "",
    ].join("\n");

    const expected = [
      "@if ($ready)",
      "  @php",
      "    $state = 'ready';",
      "  @endphp",
      "",
      "@else",
      "  <p>Waiting</p>",
      "",
      "@endif",
      "",
    ].join("\n");

    await formatEqual(
      input,
      expected,
      {
        ...WITH_PHP,
        bladeBlankLinesAroundDirectives: "always",
        bladeDirectiveBlockStyle: "multiline",
      },
      3,
    );
  });
});
